### ISSUE TITLE
(New feature) Add "Unsubscribe" in context menu of message list (right click)

### ISSUE THREAD

**Issue by jamaisx** [Amunak/thunderbird-list-unsubscribe-addon#3]
When using "thunderbird conversations" no "Unsubscribe" button appears, like in standard editor, it would be useful to have an entry in context menu. Thank you.

**Comment by Amunak** [comment]
So I looked a bit more into it. "Thunderbird Conversations" seems to be another extension, and in that sense it's kind of "their problem" that they break native functionality.

With that being said I started poking at it and at some point became too invested to not finish the feature (6c94d8028b60b0b110464735efbef5fab4e9448f), so there is now an option in the extension preferences to enable the context menu button:

![image](https://github.com/user-attachments/assets/5640671c-47dc-427f-a519-0996d647fde0)
