### ISSUE TITLE
Unsubscribe button opens blank pop up after upgrading to 128.2.1esr (debian) 

### ISSUE THREAD

**Issue by jmcclelland** [Amunak/thunderbird-list-unsubscribe-addon#4]
Thanks for the excellent add-on.

Unfortunately, after upgrading to Thunderbird 128.2.1, I get a blank pop up when I click the unsubscribe button:

![image](https://github.com/user-attachments/assets/bfde1bde-7ce3-42ee-9060-12b04555b3d7)

Any suggestions?

Jamie

**Comment by jmcclelland** [comment]
Maybe this is a clue? Could it be a css problem? 

![image](https://github.com/user-attachments/assets/d0933d86-3256-4eb6-b257-1fbcf215d64a)

I've upgraded to Thunderbird 1:128.3.0esr-1 and am still seeing the same behavior.

**Comment by Amunak** [comment]
For some reason Github didn't send me a notification for this issue, sorry.

With that being said, it "works on my machine" (Tb 128.3.2esr on Fedora Linux). I can try it later on Windows. I assume you tried restarting Tb and the behavior persists?

**Comment by jmcclelland** [comment]
It works now!! I just upgraded from 1:128.3.0 to 1:128.3.2 and now it works. I think it must have been a bug in the previous version.
